---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```


```{r data, include=FALSE}
data("instacart")

instacart = 
  instacart %>% 
  as_tibble(instacart)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>%
  group_by(order_dow, department) %>% 
  summarise(orders = n()) %>%
  ungroup() %>%
  plot_ly(
    x = ~order_dow, y = ~orders, color = ~department,
    type = "scatter", mode = "lines+markers", colors = "viridis") %>%
  layout(title = 'Number of products by day', xaxis = list(title = 'Day of the week'))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>% 
  count(department) %>% 
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(
  x = ~department, y = ~n, color = ~department,
  type = "bar", colors = "viridis") %>%
  layout(title = 'Number of items ordered in each department')
```

### Chart C

```{r}
instacart %>%
  plot_ly(
    y = ~order_hour_of_day, color = ~department,
    type = "box", colors = "viridis") %>%
    layout(title = 'Hour of order by department', xaxis = list(title = 'Department'), yaxis = list(title = 'Order hour of day'))
```

### Chart D

```{r}
instacart %>% 
  count(aisle) %>%
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(
    x = ~aisle, y = ~n,
    type = "scatter", mode = "markers") %>%
  layout(title = 'Number of items ordered in each aisle', xaxis = list(title = 'Aisle'), colors = "viridis")
```

